=== Software-Quality-Systems-Lab/Eradigitzen/schema/PerfilInnovacion_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Perfil de innovacion",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "IDENTIFICADOR_UJ": { "type": "string" },
      "PerfilExpresdeInnovacion": { "type": "boolean" },
      "PerfilAvanzadoDeInnovacion": { "type": "boolean" },
      "FechaUltimoPerfilExprex": { "type": "string", "format": "date" },
      "ResultadoGlobalDelPerfilExpres": { "type": "number", "minimum": 0, "maximum": 100 },
      "ResultadosCapacidadesPerfilExpres": { "type": "number", "minimum": 0 },
      "ResultadosActividadPerfilExpres": { "type": "number", "minimum": 0 },
      "FechaUltimoPerfilAvanzado": { "type": "string", "format": "date" },
      "ResultadoGlobalDelPerfilAvanzado": { "type": "number", "minimum": 0, "maximum": 100 },
      "ResultadoCapacidadesPerfilAvanzado": { "type": "number", "minimum": 0 },
      "ResultadoInnovacionProductoPerfilAvanzado": { "type": "number", "minimum": 0 },
      "ResultadoInnovacionProcesoPerfilAvanzado": { "type": "number", "minimum": 0 },
      "ResultadosInnovacionPersonasPerfilAvanzado": { "type": "number", "minimum": 0 },
      "ResultadosInnovacionMercadoPerfilAvanzado": { "type": "number", "minimum": 0 }
    },
    "required": [ "IDENTIFICADOR_UJ","PerfilExpresdeInnovacion", "PerfilAvanzadoDeInnovacion" ],
    "allOf": [
      {
        "if": {
          "properties": { "PerfilExpresdeInnovacion": { "const": true } }
        },
        "then": {
          "properties": {
            "FechaUltimoPerfilExprex": { "type": "string", "format": "date" },
            "ResultadoGlobalDelPerfilExpres": { "type": "number", "minimum": 0, "maximum": 100 },
            "ResultadosCapacidadesPerfilExpres": { "type": "number", "minimum": 0 },
            "ResultadosActividadPerfilExpres": { "type": "number", "minimum": 0 }
          },
          "required": ["FechaUltimoPerfilExprex", "ResultadoGlobalDelPerfilExpres", 
          "ResultadosCapacidadesPerfilExpres", "ResultadosActividadPerfilExpres"]
        },
        "else": {
          "not": {
            "anyOf": [
              { "required": ["FechaUltimoPerfilExprex"] },
              { "required": ["ResultadoGlobalDelPerfilExpres"] },
              { "required": ["ResultadosCapacidadesPerfilExpres"] },
              { "required": ["ResultadosActividadPerfilExpres"] }
            ]
          }
        }
      },
      {
        "if": {
          "properties": { "PerfilAvanzadoDeInnovacion": { "const": true } }
        },
        "then": {
          "properties": {
            "FechaUltimoPerfilAvanzado": { "type": "string", "format": "date" },
            "ResultadoGlobalDelPerfilAvanzado": { "type": "number", "minimum": 0, "maximum": 100 },
            "ResultadoCapacidadesPerfilAvanzado": { "type": "number", "minimum": 0 },
            "ResultadoInnovacionProductoPerfilAvanzado": { "type": "number", "minimum": 0 },
            "ResultadoInnovacionProcesoPerfilAvanzado": { "type": "number", "minimum": 0 },
            "ResultadosInnovacionPersonasPerfilAvanzado": { "type": "number", "minimum": 0 },
            "ResultadosInnovacionMercadoPerfilAvanzado": { "type": "number", "minimum": 0 }
          },
          "required": ["FechaUltimoPerfilAvanzado", "ResultadoGlobalDelPerfilAvanzado", "ResultadoCapacidadesPerfilAvanzado",
        "ResultadoInnovacionProductoPerfilAvanzado",  "ResultadoInnovacionProcesoPerfilAvanzado", 
        "ResultadosInnovacionPersonasPerfilAvanzado", "ResultadosInnovacionMercadoPerfilAvanzado"]
        },
        "else": {
          "not": {
            "anyOf": [
              { "required": ["FechaUltimoPerfilAvanzado"] },
              { "required": ["ResultadoGlobalDelPerfilAvanzado"] },
              { "required": ["ResultadoCapacidadesPerfilAvanzado"] },
              { "required": ["ResultadoInnovacionProductoPerfilAvanzado"] },
              { "required": ["ResultadoInnovacionProcesoPerfilAvanzado"] },
              { "required": ["ResultadosInnovacionPersonasPerfilAvanzado"] },
              { "required": ["ResultadosInnovacionMercadoPerfilAvanzado"] }
            ]
          }
        }
      }
    ],
    "additionalProperties": false
  }
}

=== Software-Quality-Systems-Lab/Eradigitzen/Innobasque/Dataset_Innobasque_1/Dataset_Innobasque_1_2.json
[
    {
      "IDENTIFICADOR_UJ": "UJ1001",
      "PerfilExpresdeInnovacion": true,
      "PerfilAvanzadoDeInnovacion": false,
      "FechaUltimoPerfilExprex": "2024-04-01",
      "ResultadoGlobalDelPerfilExpres": 78.5,
      "ResultadosCapacidadesPerfilExpres": 40.2,
      "ResultadosActividadPerfilExpres": 38.3
    },
    {
      "IDENTIFICADOR_UJ": "UJ1002",
      "PerfilExpresdeInnovacion": false,
      "PerfilAvanzadoDeInnovacion": true,
      "FechaUltimoPerfilAvanzado": "2023-12-15",
      "ResultadoGlobalDelPerfilAvanzado": 82.3,
      "ResultadoCapacidadesPerfilAvanzado": 40,
      "ResultadoInnovacionProductoPerfilAvanzado": 12,
      "ResultadoInnovacionProcesoPerfilAvanzado": 10.5,
      "ResultadosInnovacionPersonasPerfilAvanzado": 9.8,
      "ResultadosInnovacionMercadoPerfilAvanzado": 10
    },
    {
      "IDENTIFICADOR_UJ": "UJ1003",
      "PerfilExpresdeInnovacion": true,
      "PerfilAvanzadoDeInnovacion": true,
      "FechaUltimoPerfilExprex": "2024-01-22",
      "ResultadoGlobalDelPerfilExpres": 65,
      "ResultadosCapacidadesPerfilExpres": 33.3,
      "ResultadosActividadPerfilExpres": 31.7,
      "FechaUltimoPerfilAvanzado": "2024-03-18",
      "ResultadoGlobalDelPerfilAvanzado": 90.1,
      "ResultadoCapacidadesPerfilAvanzado": 45.5,
      "ResultadoInnovacionProductoPerfilAvanzado": 15,
      "ResultadoInnovacionProcesoPerfilAvanzado": 12,
      "ResultadosInnovacionPersonasPerfilAvanzado": 10,
      "ResultadosInnovacionMercadoPerfilAvanzado": 7.6
    },
    {
        "IDENTIFICADOR_UJ": "UJ1004",
        "PerfilExpresdeInnovacion": true,
        "PerfilAvanzadoDeInnovacion": true,
        "FechaUltimoPerfilExprex": "2024-02-22",
        "ResultadoGlobalDelPerfilExpres": 21,
        "ResultadosCapacidadesPerfilExpres": 12.3,
        "ResultadosActividadPerfilExpres": 3.7,
        "FechaUltimoPerfilAvanzado": "2023-03-18",
        "ResultadoGlobalDelPerfilAvanzado": 9.1,
        "ResultadoCapacidadesPerfilAvanzado": 4.5,
        "ResultadoInnovacionProductoPerfilAvanzado": 5,
        "ResultadoInnovacionProcesoPerfilAvanzado": 1,
        "ResultadosInnovacionPersonasPerfilAvanzado": 1,
        "ResultadosInnovacionMercadoPerfilAvanzado": 7.6
      },
    {
      "IDENTIFICADOR_UJ": "UJ1005",
      "PerfilExpresdeInnovacion": true,
      "PerfilAvanzadoDeInnovacion": false,
      "FechaUltimoPerfilExprex": "2023-11-30",
      "ResultadoGlobalDelPerfilExpres": 72.4,
      "ResultadosCapacidadesPerfilExpres": 36,
      "ResultadosActividadPerfilExpres": 36.4
    },
    {
      "IDENTIFICADOR_UJ": "UJ1006",
      "PerfilExpresdeInnovacion": false,
      "PerfilAvanzadoDeInnovacion": true,
      "FechaUltimoPerfilAvanzado": "2024-02-10",
      "ResultadoGlobalDelPerfilAvanzado": 88.2,
      "ResultadoCapacidadesPerfilAvanzado": 42,
      "ResultadoInnovacionProductoPerfilAvanzado": 14,
      "ResultadoInnovacionProcesoPerfilAvanzado": 11.5,
      "ResultadosInnovacionPersonasPerfilAvanzado": 10.1,
      "ResultadosInnovacionMercadoPerfilAvanzado": 10.6
    },
    {
        "IDENTIFICADOR_UJ": "UJ1007",
        "PerfilExpresdeInnovacion": false,
        "PerfilAvanzadoDeInnovacion": true,
        "FechaUltimoPerfilAvanzado": "2023-02-10",
        "ResultadoGlobalDelPerfilAvanzado": 10.2,
        "ResultadoCapacidadesPerfilAvanzado": 22,
        "ResultadoInnovacionProductoPerfilAvanzado": 14,
        "ResultadoInnovacionProcesoPerfilAvanzado": 9.5,
        "ResultadosInnovacionPersonasPerfilAvanzado": 2.1,
        "ResultadosInnovacionMercadoPerfilAvanzado": 10.6
      },
    {
      "IDENTIFICADOR_UJ": "UJ1008",
      "PerfilExpresdeInnovacion": true,
      "PerfilAvanzadoDeInnovacion": true,
      "FechaUltimoPerfilExprex": "2023-10-11",
      "ResultadoGlobalDelPerfilExpres": 55.7,
      "ResultadosCapacidadesPerfilExpres": 27.5,
      "ResultadosActividadPerfilExpres": 28.2,
      "FechaUltimoPerfilAvanzado": "2024-01-05",
      "ResultadoGlobalDelPerfilAvanzado": 76,
      "ResultadoCapacidadesPerfilAvanzado": 38,
      "ResultadoInnovacionProductoPerfilAvanzado": 11,
      "ResultadoInnovacionProcesoPerfilAvanzado": 10,
      "ResultadosInnovacionPersonasPerfilAvanzado": 9,
      "ResultadosInnovacionMercadoPerfilAvanzado": 8
    },
    {
        "IDENTIFICADOR_UJ": "UJ1009",
        "PerfilExpresdeInnovacion": true,
        "PerfilAvanzadoDeInnovacion": false,
        "FechaUltimoPerfilExprex": "2024-02-05",
        "ResultadoGlobalDelPerfilExpres": 35.9,
        "ResultadosCapacidadesPerfilExpres": 30,
        "ResultadosActividadPerfilExpres": 21.9
      },
    {
      "IDENTIFICADOR_UJ": "UJ1010",
      "PerfilExpresdeInnovacion": true,
      "PerfilAvanzadoDeInnovacion": false,
      "FechaUltimoPerfilExprex": "2024-03-05",
      "ResultadoGlobalDelPerfilExpres": 61.9,
      "ResultadosCapacidadesPerfilExpres": 30,
      "ResultadosActividadPerfilExpres": 31.9
    }
  ]
